
const selectors = {
  name: '.contact-info__title-name',
  subtitleName: '.contact-info__subtitle-name',
  contactTextLocation: '.list__contact-text-location',
  skillsTitleSoft: '.skills__title-soft',
  skillsTitleLang: '.skills__title-lang',
  skillsFontOne: '.skills__font-one',
  skillsFontTwo: '.skills__font-two',
  contentTitle: '.content__title',
  contentText: '.content__text',
  contentTitleEducation: '.content__title-education',
  contentWellOne: '.content__well-one',
  contentTimePeriodOne: '.content__time-period-one',
  contentWellTwo: '.content__well-two',
  contentTimePeriodTwo: '.content__time-period-two',
  contentDescriptionOne: '.content__description-one',
  contentDescriptionTwo: '.content__description-two',
  contentTitleSertificats: '.content__title-sertificats',
  contentAboutMyself: '.content__about-myself',
  contentAboutOne: '.content__about-one',
  contentAboutTwo: '.content__about-two',
  hardSkillsTitle: '.hard-skills__title',
  skillsQualityItem1: '.skills__quality-item1',
  skillsQualityItem2: '.skills__quality-item2',
  skillsQualityItem3: '.skills__quality-item3',
  skillsQualityItem4: '.skills__quality-item4',
  skillsQualityItem5: '.skills__quality-item5',
  skillsQualityItem6: '.skills__quality-item6',
};

const valuesRU = {
  name: 'КАНОПЛИЧ АНДРЕЙ',
  subtitleName: 'JUNIOR FRONTEND разработчик',
  contactTextLocation: 'г. Минск',
  skillsTitleSoft: 'Ключевые Навыки',
  skillsTitleLang: 'Языки',
  skillsFontOne: 'Русский',
  skillsFontTwo: 'Английский',
  contentTitle: 'Желаемая должность',
  contentText: 'JUNIOR FRONTEND разработчик',
  contentTitleEducation: 'Образование',
  contentWellOne: 'IT-Academy Образовательный центр программирования и высоких технологий.',
  contentTimePeriodOne: 'авг.2021-нояб.2021',
  contentWellTwo: 'IT-Academy Образовательный центр программирования и высоких технологий.',
  contentTimePeriodTwo: 'янв.2022-апр.2022',
  contentDescriptionOne:
    'Успешно окончил курс "Разработка веб-сайтов с использованием HTML, CSS и JavaScript".',
  contentDescriptionTwo: 'Успешно окончил курс "Разработка веб-приложений на JavaScript".',
  contentTitleSertificats: 'Сертификаты',
  contentAboutMyself: 'О себе',
  contentAboutOne:
    'На данный момент ищу либо стажировку, либо позицию Junior Frontend разработчика.',
  contentAboutTwo:
    'Хотел бы стать частью дружной и профессиональной команды, в которой я мог бы развивать свои навыки разработки для достижения командных и личных результатов.',
  hardSkillsTitle: 'Качества',
  skillsQualityItem1: 'Ответственность',
  skillsQualityItem2: 'Работа в команде',
  skillsQualityItem3: 'Трудолюбие',
  skillsQualityItem4: 'Быстрая обучаемость',
  skillsQualityItem5: 'Желание учиться и развиваться',
  skillsQualityItem6: 'Самоорганизация',
};

const valuesEN = {
  name: 'KANOPLICH ANDREY',
  subtitleName: 'JUNIOR FRONTEND DEVELOPER',
  contactTextLocation: 'Minsk',
  skillsTitleSoft: 'Key skills',
  skillsTitleLang: 'Languages',
  skillsFontOne: 'Russian',
  skillsFontTwo: 'English',
  contentTitle: 'Career objective',
  contentText: 'Junior Frontend Developer',
  contentTitleEducation: 'Education',
  contentWellOne: 'IT-Academy Educational center for programming and high technologies.',
  contentTimePeriodOne: 'aug.2021-nov.2021',
  contentWellTwo: 'IT-Academy Educational center for programming and high technologies.',
  contentTimePeriodTwo: 'jan.2022-apr.2022',
  contentDescriptionOne:
    'Successfully completed the course "Web Development with HTML, CSS and JavaScript',
  contentDescriptionTwo:
    'Successfully completed the course "Web Application Development with JavaScript".',
  contentTitleSertificats: 'Certificates',
  contentAboutMyself: 'About myself',
  contentAboutOne:
    'At the moment I am looking for either an internship or a Junior Frontend developer position.',
  contentAboutTwo:
    'I would like to be part of a friendly and professional team where I could develop my development skills to achieve team and personal results.',
  hardSkillsTitle: 'Qualities',
  skillsQualityItem1: 'Responsibility',
  skillsQualityItem2: 'Teamwork',
  skillsQualityItem3: 'Industriousness',
  skillsQualityItem4: 'Fast learner',
  skillsQualityItem5: 'Desire to learn and develop',
  skillsQualityItem6: 'Self-organization',
};
